### ISSUE TITLE
status check

### ISSUE THREAD

**Issue by cpgmedialab** [CityScope/CS_Cooper-Hewitt#101] opened 2018-11-24 19:13 UTC
| time | who | status |
| --- | --- | --- |
| 11/24 Sat 2:10pm | Yasushi | all green 👍  (??)| 
| 11/25 Sun 2:10pm | Yasushi | *1 **scanner version miss match** | 
| 11/25 Sun 5:00pm | Yasushi & Arnaud | scanner reboot, flipping corners, all green |

**Comment by yasushisakai** [comment] 2018-11-25 19:14
**1** :

- scanner working,
- slider working
- network alive (by the fact the slider was updating in unity)
- **building types not updating**
- overhead projection was off, couldn't exactly see if they matched.

**Comment by cpgmedialab** [comment] 2018-11-25 19:45
@yasushisakai 's remark came from https://github.com/RELNO/CityScope_Scanner_Python/issues/6

**Comment by RELNO** [comment] 2018-11-25 20:10
@yasushisakai my best guess is that  @popabczhang  @Carsonsmuts edit to add a separated UDP channel for Unity was never PRed/pushed. Therefore, if the mac pro machine is now running the Scanner's master or any other commit, unity won't display interaction.

**Comment by popabczhang** [comment] 2018-11-25 20:15
> @yasushisakai my best guess is that @popabczhang @Carsonsmuts edit to add a separated UDP channel for Unity was never PRed/pushed. Therefore, if the mac pro machine is now running the Scanner's master or any other commit, unity won't display interaction.

That sounds right. Let's keep it running for stress test until tomorrow morning. Tomorrow let's have a try to see if Processing and Unity can listen to the same port (highly likely because they are on the different machines now). I will update you @RELNO if I succeed or not.

**Comment by cpgmedialab** [comment] 2018-11-25 20:17
ok, at least we have a guess. Status is red now (not sure from when)

**Comment by popabczhang** [comment] 2018-11-25 20:17
> time	who	status
> 11/24 Sat 2:10pm	Yasushi	all green 👍
> 11/25 Sun 2:10pm	Yasushi	*1

@yasushisakai, does "11/24 Sat 2:10pm	Yasushi	all green" mean the building types changed correctly on Sat?

**Comment by yasushisakai** [comment] 2018-11-25 20:20
thing is, not sure. I remember I saw it has responded. Don't remember if the buildings were synced (for both). 

Friday night (time unknown) it was working.

**Comment by RELNO** [comment] 2018-11-25 20:21
@yasushisakai if the mac pro is running the same scanner version as on your last status check, the problem is NOT what I've described. If otherwise you've pulled a new commit, then it might explain. Can you verify?

**Comment by Carsonsmuts** [comment] 2018-11-25 20:34
I was in this morning Sunday 25th 11:30am. Everything was working fine. I moved the slider and both Processing and Unity followed the slider line, and as far as I could tell everything looked good for a stress test.

**Comment by Carsonsmuts** [comment] 2018-11-25 20:35
> @yasushisakai my best guess is that @popabczhang @Carsonsmuts edit to add a separated UDP channel for Unity was never PRed/pushed. Therefore, if the mac pro machine is now running the Scanner's master or any other commit, unity won't display interaction.

Everything was reacting normally to interaction this morning. Testing in **person** at the lab 11:30am Sunday 25th

**Comment by cpgmedialab** [comment] 2018-11-25 20:38
@Carsonsmuts slider was and is working fine. 
Did you observe the building mismatch?

Y.S.

**Comment by Carsonsmuts** [comment] 2018-11-25 20:49
> @Carsonsmuts slider was and is working fine.
> Did you observe the building mismatch?
> 
> Y.S.

I see.... I was preoccupied with the communication pipeline and the stability of the software. I only checked to see that the **two computers** were still talking **over the wireless router** and that both **processing and unity were updating**. Whether the data for the buildings was correct, I did not observe any mismatch, but keep in mind I was looking elsewhere for issues.

**Comment by yasushisakai** [comment] 2018-11-26 02:33
@Carsonsmuts Yup, the network was stable. I think we just want the commit id or a tag for each component, so we make sure we run the right one.

Table state has recovered, by flipping the corners of ```keystone.py``` of the scanner

**Comment by agrignard** [comment] 2018-11-26 12:28
duplicate with #83 (needs to keep only one issue) even if a status ceck is not really an issue it's more a report.

**Comment by RELNO** [comment] 2018-11-26 16:43
Putting everyone on the same page: 
https://github.com/RELNO/CityScope_Scanner_Python/commit/70255a2a34f9f566dc61c3edb37ea04df6c1630c merged two [sort of] major changes which needed to be stress-tested: 

- sending to two UDP clients 
- halting UDP send for 30ms after detecting a change to either grid or slider

**Comment by agrignard** [comment] 2018-11-27 02:09
hard to maintain as an issue (not reproductible, nothing to "fix")

I think now the status is the table is working by default if not a dedicated issue is created

**Closed as completed by agrignard** 2018-11-27 02:09 UTC
