### ISSUE TITLE
First surface Mirror sizes

### ISSUE THREAD

**Issue by LAAP** [CityScope/CS_Cooper-Hewitt#11] opened 2018-10-17 15:07 UTC
Size of the first surface Mirror is needed, so it can be ordered.

**Comment by yasushisakai** [comment] 2018-10-20 22:04
was this ordered?

**Comment by LAAP** [comment] 2018-10-20 23:47
The dimensions are 31x45cm. We found the online shop; (https://firstsurfacemirror.com/glass-first-surface-mirror/) but it is not in Amazon, so Carson needs to talk with Mary....

**Comment by Carsonsmuts** [comment] 2018-10-21 00:34
Correct, I cannot order using the card.

I’ll chat to her on Monday, I have to talk to Mary about Unity3D quote anyway.

C

**Comment by LAAP** [comment] 2018-10-21 16:15
Awesome! Thanks! I can be with you going through this "Intense experience"

**Comment by yasushisakai** [comment] 2018-10-26 20:05
related to #22

**Comment by Carsonsmuts** [comment] 2018-10-26 20:21
Lets order all the mirrors in one shot.

**Comment by agrignard** [comment] 2018-11-05 02:04
Duplicate of #56

**Closed as completed** 2018-11-05 02:04 UTC
Labels: Hardware, Scanning
