### ISSUE TITLE
JSONArray[0] is not a JSONArray.

### ISSUE THREAD

**Issue by cpgmedialab** [CityScope/CS_Cooper-Hewitt#74] opened 2018-11-13 22:18 UTC
Simulation was found dead with the error of this issues subject
Grid.pde line 45 

Y.S.

**Comment by agrignard** [comment] 2018-11-14 00:26
Was it from the last master? line 45 is          b.draw(p); so it's weird.

It might be related to the update of the grid and the Json receive by the scanner

CAn you dig a bit more? is it happening at the initialization or after a while?

**Comment by agrignard** [comment] 2018-11-14 11:04
I cannot reproduce this bug on my machine.

**Comment by yasushisakai** [comment] 2018-11-14 16:39
I suspect this is a parsing error between the scanner. Will be watching for this.

**Comment by agrignard** [comment] 2018-11-15 16:43
I close this one, Felle free to reopen if it rehappens

**Comment by agrignard** [comment] 2018-11-15 16:43
I close this one, fell free to reopen if it rehappens

**Closed as completed by agrignard** 2018-11-15 16:43 UTC
Labels: bug, ABMobility
