### ISSUE TITLE
bottom projector and mirror location

### ISSUE THREAD

**Issue by yasushisakai** [CityScope/CS_Cooper-Hewitt#22] opened 2018-10-23 04:21 UTC
The middle and edge pixel is very different giving a large resolution loss at the middle of the table.

To minimize this, I would like to flip and test the projector normal (not upside down) + angled solution. As a result, we will need larger mirror area which need to be carefully see it is not occluding the scanner camera frustum.

**Comment by yasushisakai** [comment] 2018-10-26 20:02
to try an alternate way, Markus has ordered the projector mounts for the bottom.
Let's see how this will work

**Comment by Carsonsmuts** [comment] 2018-10-26 20:22
We need three mirrors. Do we know what the top down mirror must be? And if the bottom mirrors are changing, what are those new sizes?

**Comment by RELNO** [comment] 2018-10-30 00:38
![img_2333](https://user-images.githubusercontent.com/14296774/47688165-69c94c00-dbba-11e8-8a41-4ecbaf4b244a.JPG)
This is the ceiling design per @guadalupebabio visit -- can this be a solution for the upper mirror?

**Comment by agrignard** [comment] 2018-11-05 02:04
Duplicate of #56

**Closed as completed by agrignard** 2018-11-05 02:04 UTC
Labels: ABMobility, Hardware, Scanning
