### ISSUE TITLE
[Oct 29 meeting follow up] permanent fixing of webcam is needed  

### ISSUE THREAD

**Issue by RELNO** [CityScope/CS_Cooper-Hewitt#37] opened 2018-10-30 00:16 UTC

**Comment by Carsonsmuts** [comment] 2018-10-30 03:30
If everyone is happy with the location then yes, we can fix it permanently. How high off the ground is currently an acceptable distance? When I cut plates for table later this week, I was planning on cutting support plates for the camera.

**Comment by RELNO** [comment] 2018-10-30 13:33
@Carsonsmuts thanks! as long as we get the scanning area, any above the ground setup will do
<img width="1031" alt="cam00001" src="https://user-images.githubusercontent.com/14296774/47721586-cfebb880-dc26-11e8-9feb-90aa41848a6a.png">

**Comment by agrignard** [comment] 2018-11-05 02:04
Duplicate of #56

**Closed as completed** 2018-11-05 02:04 UTC
Labels: Hardware, Scanning
